from fastapi import APIRouter
router=APIRouter(prefix="/api/tools", tags=["tools"])
TOOLS=[
 {"id":"merge","name":"Merge PDF","category":"Organize","description":"Combine multiple PDFs into one","accepts":[".pdf"]},
 {"id":"split","name":"Split PDF","category":"Organize","description":"Split PDF into single pages (ZIP)","accepts":[".pdf"]},
 {"id":"extract-pages","name":"Extract Pages","category":"Organize","description":"Extract selected pages","accepts":[".pdf"]},
 {"id":"delete-pages","name":"Delete Pages","category":"Organize","description":"Remove selected pages","accepts":[".pdf"]},
 {"id":"reorder","name":"Reorder / Workspace","category":"Organize","description":"Reorder / workspace","accepts":[".pdf"]},
 {"id":"rotate","name":"Rotate PDF","category":"Organize","description":"Rotate all pages","accepts":[".pdf"]},
 {"id":"compress","name":"Compress PDF","category":"Compress","description":"Optimize and compress","accepts":[".pdf"]},
 {"id":"pdf-to-image","name":"PDF to JPG/PNG","category":"Convert","description":"Export pages as images (ZIP)","accepts":[".pdf"]},
 {"id":"image-to-pdf","name":"JPG/PNG to PDF","category":"Convert","description":"Images to PDF","accepts":[".jpg",".jpeg",".png"]},
 {"id":"protect","name":"Protect PDF","category":"Security","description":"Add password","accepts":[".pdf"]},
 {"id":"unlock","name":"Unlock PDF","category":"Security","description":"Remove password","accepts":[".pdf"]},
 {"id":"watermark","name":"Watermark","category":"Edit","description":"Add text watermark","accepts":[".pdf"]},
 {"id":"remove-watermark","name":"Remove Watermark","category":"Edit","description":"Hapus watermark text/gambar","accepts":[".pdf"]},
 {"id":"page-numbers","name":"Page Numbers","category":"Edit","description":"Add page numbers","accepts":[".pdf"]},
 {"id":"pdf-to-csv","name":"PDF → CSV","category":"Data","description":"Extract tables to CSV with delimiter & preview","accepts":[".pdf"]},
 {"id":"pdf-to-excel","name":"PDF → Excel","category":"Data","description":"Extract tables to XLSX (Excel) with preview","accepts":[".pdf"]},
 {"id":"pdf-to-excel-cam","name":"PDF → Excel CAM","category":"Converter","description":"Khusus Detail CAM Prioritisasi: hapus watermark otomatis lalu gabungkan semua halaman ke 1 sheet Excel (32 kolom baku)","accepts":[".pdf"]},
 {"id":"md-to-pdf","name":"Markdown → PDF","category":"Document","description":"Markdown with live preview to PDF","accepts":[".md"]},
 {"id":"html-to-pdf","name":"HTML → PDF","category":"Document","description":"HTML/CSS to PDF","accepts":[".html",".htm"]},
 {"id":"mp3-trim","name":"Trim MP3","category":"Media","description":"Cut MP3 by time range with preview","accepts":[".mp3"]},
 {"id":"video-downloader","name":"Video / MP3 Downloader","category":"Media","description":"Download video (MP4) or audio (MP3) from YouTube, Twitter, Instagram, and 1000+ sites","accepts":[]},
 # Stirling-mapped additional tools (design unchanged)
 {"id":"cert-sign","name":"Cert Sign","category":"Security","description":"Digital certificate sign (stub)","accepts":[".pdf"]},
 {"id":"sign","name":"Sign PDF","category":"Security","description":"Add signature image","accepts":[".pdf"]},
 {"id":"add-text","name":"Add Text","category":"Edit","description":"Add text annotations","accepts":[".pdf"]},
 {"id":"remove-blanks","name":"Remove Blanks","category":"Organize","description":"Remove blank pages","accepts":[".pdf"]},
 {"id":"remove-annotations","name":"Remove Annotations","category":"Edit","description":"Remove annotations/comments","accepts":[".pdf"]},
 {"id":"remove-image","name":"Remove Images","category":"Edit","description":"Remove embedded images","accepts":[".pdf"]},
 {"id":"change-permissions","name":"Change Permissions","category":"Security","description":"Update PDF permissions","accepts":[".pdf"]},
 {"id":"sanitize","name":"Sanitize PDF","category":"Security","description":"Remove hidden data","accepts":[".pdf"]},
 {"id":"ocr","name":"OCR PDF","category":"Data","description":"Make scanned PDF searchable (Tesseract)","accepts":[".pdf"]},
 {"id":"add-image","name":"Add Image","category":"Edit","description":"Insert image into PDF","accepts":[".pdf",".png",".jpg"]},
 {"id":"auto-rotate","name":"Auto Rotate","category":"Organize","description":"Auto-detect & rotate","accepts":[".pdf"]},
 {"id":"crop","name":"Crop PDF","category":"Edit","description":"Crop page margins","accepts":[".pdf"]},
 {"id":"repair","name":"Repair PDF","category":"Organize","description":"Repair corrupted PDF","accepts":[".pdf"]},
 {"id":"flatten","name":"Flatten PDF","category":"Edit","description":"Flatten forms & annotations","accepts":[".pdf"]},
 {"id":"compare","name":"Compare PDFs","category":"Data","description":"Diff two PDFs","accepts":[".pdf"]},
 {"id":"redact","name":"Redact PDF","category":"Security","description":"Permanent redaction","accepts":[".pdf"]},
 {"id":"extract-images","name":"Extract Images","category":"Data","description":"Extract embedded images (ZIP)","accepts":[".pdf"]},
 {"id":"add-stamp","name":"Add Stamp","category":"Edit","description":"Add stamp overlay","accepts":[".pdf"]},
 {"id":"add-attachments","name":"Add Attachments","category":"Edit","description":"Attach files to PDF","accepts":[".pdf"]},
 {"id":"change-metadata","name":"Change Metadata","category":"Edit","description":"Edit title/author/metadata","accepts":[".pdf"]},
 {"id":"overlay-pdfs","name":"Overlay PDFs","category":"Organize","description":"Overlay one PDF onto another","accepts":[".pdf"]},
 {"id":"get-pdf-info","name":"PDF Info","category":"Data","description":"Show metadata & page count","accepts":[".pdf"]},
 {"id":"validate-signature","name":"Validate Signature","category":"Security","description":"Validate digital signatures","accepts":[".pdf"]},
 {"id":"remove-cert-sign","name":"Remove Cert Sign","category":"Security","description":"Remove certificate signatures","accepts":[".pdf"]},
 {"id":"unlock-pdf-forms","name":"Unlock Forms","category":"Security","description":"Unlock PDF form fields","accepts":[".pdf"]},
 {"id":"reorganize-pages","name":"Reorganize Pages","category":"Organize","description":"Reorder via visual layout","accepts":[".pdf"]},
 {"id":"page-layout","name":"Page Layout","category":"Organize","description":"Change page layout / imposition","accepts":[".pdf"]},
 {"id":"scale-pages","name":"Scale Pages","category":"Edit","description":"Scale page dimensions","accepts":[".pdf"]},
 {"id":"replace-color","name":"Replace Color","category":"Edit","description":"Replace colors in PDF","accepts":[".pdf"]},
 {"id":"booklet-imposition","name":"Booklet Imposition","category":"Organize","description":"Booklet printing layout","accepts":[".pdf"]},
 {"id":"pdf-text-editor","name":"PDF Text Editor","category":"Edit","description":"Edit PDF text (beta)","accepts":[".pdf"]},
 {"id":"auto-rename","name":"Auto Rename","category":"Organize","description":"Auto-rename by content","accepts":[".pdf"]},
 {"id":"scanner-effect","name":"Scanner Effect","category":"Edit","description":"Add scanner look","accepts":[".pdf"]},
 {"id":"adjust-contrast","name":"Adjust Contrast","category":"Edit","description":"Adjust page contrast","accepts":[".pdf"]},
 {"id":"pdf-to-single-page","name":"PDF to Single Page","category":"Organize","description":"Merge pages vertically","accepts":[".pdf"]},
 {"id":"show-js","name":"Show JavaScript","category":"Security","description":"Show embedded JS","accepts":[".pdf"]},
]
@router.get("")
def list_tools(): return TOOLS
@router.get("/{tid}")
def get_tool(tid:str):
    for t in TOOLS:
        if t["id"]==tid: return t
    return {"error":"not found"}
