import axios from 'axios'
export const api = axios.create({ baseURL: '' })
api.interceptors.request.use(c=>{ const t=localStorage.getItem('token'); if(t) c.headers.Authorization=`Bearer ${t}`; return c})
export const toolsList = [
  // Stirling-mapped: keep original 18 + add 35+ from CORE_REGULAR_TOOL_IDS, design unchanged (brand cards)
  {id:'merge',name:'Merge PDF',cat:'Organize',icon:'Combine', desc:'Combine multiple PDFs into one'},
  {id:'split',name:'Split PDF',cat:'Organize',icon:'Scissors', desc:'Split by pages, size, chapters'},
  {id:'extract-pages',name:'Extract Pages',cat:'Organize',icon:'Copy', desc:'Extract specific pages'},
  {id:'delete-pages',name:'Delete Pages',cat:'Organize',icon:'Trash', desc:'Remove selected pages'},
  {id:'rotate',name:'Rotate PDF',cat:'Organize',icon:'RotateCw', desc:'Rotate 90/180/270°'},
  {id:'reorder',name:'Reorder / Workspace',cat:'Organize',icon:'Grip', desc:'Drag-drop reorder workspace'},
  {id:'compress',name:'Compress PDF',cat:'Compress',icon:'Minimize2', desc:'Optimize size & DPI'},
  {id:'pdf-to-image',name:'PDF → Images',cat:'Convert',icon:'Image', desc:'Export pages as JPG/PNG'},
  {id:'image-to-pdf',name:'Images → PDF',cat:'Convert',icon:'FileImage', desc:'Images to PDF'},
  {id:'protect',name:'Protect PDF',cat:'Security',icon:'Lock', desc:'Add password (Stirling: addPassword)'},
  {id:'unlock',name:'Unlock PDF',cat:'Security',icon:'Unlock', desc:'Remove password'},
  {id:'watermark',name:'Watermark',cat:'Edit',icon:'Droplet', desc:'Add text watermark'},
  {id:'remove-watermark',name:'Remove Watermark',cat:'Edit',icon:'Eraser', desc:'Hapus watermark text/gambar'},
  {id:'page-numbers',name:'Page Numbers',cat:'Edit',icon:'Hash', desc:'Add page numbers'},
  {id:'pdf-to-csv',name:'PDF → CSV',cat:'Data',icon:'Table', desc:'Extract tables to CSV'},
  {id:'pdf-to-excel',name:'PDF → Excel',cat:'Data',icon:'Table', desc:'Tables to XLSX'},
  {id:'pdf-to-excel-cam',name:'PDF → Excel CAM',cat:'Convert',icon:'Table', desc:'Khusus Detail CAM Prioritisasi: hapus watermark + semua halaman jadi 1 sheet'},
  {id:'md-to-pdf',name:'Markdown → PDF',cat:'Document',icon:'FileText', desc:'Markdown to PDF'},
  {id:'html-to-pdf',name:'HTML → PDF',cat:'Document',icon:'Code', desc:'HTML/CSS to PDF'},
  {id:'mp3-trim',name:'Trim MP3',cat:'Media',icon:'Music', desc:'Cut MP3 by time'},
  {id:'video-downloader',name:'Video / MP3 Downloader',cat:'Media',icon:'Video', desc:'Download video (MP4) or audio (MP3) from YouTube, Twitter, Instagram, 1000+ sites'},
  // Additional Stirling Tools — same design cards, backend stubs or real engines
  {id:'cert-sign',name:'Cert Sign',cat:'Security',icon:'Shield', desc:'Digital certificate sign'},
  {id:'sign',name:'Sign PDF',cat:'Security',icon:'Pen', desc:'Add signature image'},
  {id:'add-text',name:'Add Text',cat:'Edit',icon:'Type', desc:'Add text annotations'},
  {id:'remove-blanks',name:'Remove Blanks',cat:'Organize',icon:'Eraser', desc:'Remove blank pages'},
  {id:'remove-annotations',name:'Remove Annotations',cat:'Edit',icon:'X', desc:'Remove annotations/comments'},
  {id:'remove-image',name:'Remove Images',cat:'Edit',icon:'ImageOff', desc:'Remove embedded images'},
  {id:'change-permissions',name:'Change Permissions',cat:'Security',icon:'Key', desc:'Update PDF permissions'},
  {id:'sanitize',name:'Sanitize PDF',cat:'Security',icon:'ShieldCheck', desc:'Remove hidden data'},
  {id:'ocr',name:'OCR PDF',cat:'Data',icon:'Scan', desc:'Make scanned PDF searchable'},
  {id:'add-image',name:'Add Image',cat:'Edit',icon:'ImagePlus', desc:'Insert image into PDF'},
  {id:'auto-rotate',name:'Auto Rotate',cat:'Organize',icon:'RefreshCw', desc:'Auto-detect & rotate'},
  {id:'crop',name:'Crop PDF',cat:'Edit',icon:'Crop', desc:'Crop page margins'},
  {id:'repair',name:'Repair PDF',cat:'Organize',icon:'Wrench', desc:'Repair corrupted PDF'},
  {id:'flatten',name:'Flatten PDF',cat:'Edit',icon:'Layers', desc:'Flatten forms & annotations'},
  {id:'compare',name:'Compare PDFs',cat:'Data',icon:'GitCompare', desc:'Diff two PDFs'},
  {id:'redact',name:'Redact PDF',cat:'Security',icon:'EyeOff', desc:'Permanent redaction'},
  {id:'extract-images',name:'Extract Images',cat:'Data',icon:'Images', desc:'Extract embedded images (ZIP)'},
  {id:'add-stamp',name:'Add Stamp',cat:'Edit',icon:'Stamp', desc:'Add stamp overlay'},
  {id:'add-attachments',name:'Add Attachments',cat:'Edit',icon:'Paperclip', desc:'Attach files to PDF'},
  {id:'change-metadata',name:'Change Metadata',cat:'Edit',icon:'Info', desc:'Edit title/author/metadata'},
  {id:'overlay-pdfs',name:'Overlay PDFs',cat:'Organize',icon:'Layers', desc:'Overlay one PDF onto another'},
  {id:'get-pdf-info',name:'PDF Info',cat:'Data',icon:'FileInfo', desc:'Show metadata & page count'},
  {id:'validate-signature',name:'Validate Signature',cat:'Security',icon:'Check', desc:'Validate digital signatures'},
  {id:'remove-cert-sign',name:'Remove Cert Sign',cat:'Security',icon:'XCircle', desc:'Remove certificate signatures'},
  {id:'unlock-pdf-forms',name:'Unlock Forms',cat:'Security',icon:'Unlock', desc:'Unlock PDF form fields'},
  {id:'reorganize-pages',name:'Reorganize Pages',cat:'Organize',icon:'Shuffle', desc:'Reorder via visual layout'},
  {id:'page-layout',name:'Page Layout',cat:'Organize',icon:'Layout', desc:'Change page layout / imposition'},
  {id:'scale-pages',name:'Scale Pages',cat:'Edit',icon:'Maximize', desc:'Scale page dimensions'},
  {id:'replace-color',name:'Replace Color',cat:'Edit',icon:'Palette', desc:'Replace colors in PDF'},
  {id:'booklet-imposition',name:'Booklet Imposition',cat:'Organize',icon:'Book', desc:'Booklet printing layout'},
  {id:'pdf-text-editor',name:'PDF Text Editor',cat:'Edit',icon:'Edit', desc:'Edit PDF text (beta)'},
  {id:'auto-rename',name:'Auto Rename',cat:'Organize',icon:'Tag', desc:'Auto-rename by content'},
  {id:'scanner-effect',name:'Scanner Effect',cat:'Edit',icon:'Scan', desc:'Add scanner look'},
  {id:'adjust-contrast',name:'Adjust Contrast',cat:'Edit',icon:'Contrast', desc:'Adjust page contrast'},
  {id:'pdf-to-single-page',name:'PDF to Single Page',cat:'Organize',icon:'Combine', desc:'Merge pages vertically'},
  {id:'show-js',name:'Show JavaScript',cat:'Security',icon:'Code', desc:'Show embedded JS'},
]
